[package]
name = "pdf"
version = "0.1.0"
authors = ["Connor Skees <connor1skees@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fast-float = "0.2.0"
flate2 = "1.0.20"
